---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build_and_push
  image: docker:18.06-dind
  privileged: true
  environment:
    USERNAME:
      from_secret: DH_USER
    PASSWORD:
      from_secret: DH_PASS
  commands:
    - apk add --no-cache make
    - make build
    #- make push
  volumes:
    - name: docker
      path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
