---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: build_and_push
  image: ubuntu
  commands:
    - apt-get update && apt-get install -y make
    - make build
    - make push
