---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: build_and_push
  image: docker:18.06-dind
  priviliged: true
  commands:
    - apk add --no-cache make
    - make build
    - make push
